Feature/12 reccomend view
DO-NOTTO-DO/NotToDo-AOS pull request #39
Opened 2023-01-07 12:47 UTC by Mingmin99

## 👻 작업한 내용

recommend view pr 올려요

## 🎤 PR Point

## 📸 스크린샷

|    구현 내용    |   스크린샷   |
| :-------------: | :----------: |
| 어쩌고저쩌고 | 어쩌고저쩌고 |

## 📮 관련 이슈

- Resolved: #

2023-01-07 13:03 UTC, giovannijunseokim commented on app/src/main/java/kr/co/nottodo/presentation/MainActivity.kt
> +                    R.id.menu_recommend -> RecommendationFragment()
추천 뷰도 연동되다니... 끝이 머지(merge아님)않았다...!

2023-01-07 13:23 UTC, giovannijunseokim commented on app/src/main/java/kr/co/nottodo/presentation/toplevel/recommendation/RecommendationFragment.kt
> +            Log.d("ssong-develop","hello!")
Log를 사용한 후 테스트가 완료되었다면 지워주세요 !

2023-01-07 13:52 UTC, giovannijunseokim commented on app/src/main/java/kr/co/nottodo/presentation/toplevel/recommendation/RecommendationFragment.kt
> +    }
이부분 쓰지 않는다면 지워주세요 !

2023-01-07 13:55 UTC, giovannijunseokim commented on app/src/main/java/kr/co/nottodo/presentation/toplevel/recommendation/RecommendationAdapter.kt
> +                    selectedPosition
이 부분은 어떤 코드인가요 ??

2023-01-07 14:02 UTC, giovannijunseokim commented on app/src/main/java/kr/co/nottodo/presentation/toplevel/recommendation/RecommendationAdapter.kt
> +            executePendingBindings()
이 함수는 혹시 어떤 함수인가요?

2023-01-07 14:05 UTC, giovannijunseokim requested changes
돌아가는 것에 의의를 둡시다. 수고하셨습니다 !!
말씀드린 부분 반영 후 다시 PUSH 부탁드립니다 ~~~

2023-01-07 14:32 UTC, l2hyunwoo commented on app/src/main/java/kr/co/nottodo/presentation/toplevel/recommendation/RecommendationAdapter.kt
> +            executePendingBindings()
데이터 바인딩을 활용하면 새롭게 설정된 데이터가 반영될 때 비동기 식으로 한 프레임 늦게 들어가. 그런데 이걸 동기적으로 반영시키고 싶으면 밀려있는 실행해야하는 것들을 한방에 실행시켜주게 하기 위한 뚫어뻥 비슷한 격의 함수라고 생각하면 좋음

2023-01-07 14:33 UTC, l2hyunwoo commented on app/src/main/java/kr/co/nottodo/presentation/toplevel/recommendation/RecommendationFragment.kt
> +        })
```suggestion
        parentAdapter = RecommendationParentAdapter { view, childData ->
            Log.d("ssong-develop","hello!")
        }
```

이런식으로 사용할 수 있습니다.

2023-01-09 05:49 UTC, shb03323 commented on app/src/main/java/kr/co/nottodo/presentation/toplevel/recommendation/RecommendationFragment.kt
> +        })
누누님 저희 서버도 코드리뷰 해주세요.

2023-01-10 10:46 UTC, giovannijunseokim commented on app/src/main/java/kr/co/nottodo/presentation/toplevel/recommendation/RecommendationAdapter.kt
> +            executePendingBindings()
와우... 배워갑니다 !

2023-01-10 17:04 UTC, closed without merging